version: '3.7'

services:
    backend:
        container_name: backend-api
        build: ./backend-api/simple-api-student
        networks: 
        - app-network
        depends_on:
        - database

    database: 
        container_name: my_postgrey_app
        build: ./database
        networks: 
        - app-network

    httpd:
        container_name : frontend_app
        build: ./frontend-api
        ports: 
        - "8082:80"
        networks: 
        - app-network
        depends_on:
        - database
        - backend

networks:
    app-network:
